import React from "react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/server/trpc/Provider";
import Navbar from "@/components/navbar/Navbar";

import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryProvider>
            <html lang="en" className="dark">
                <body
                    className={`${inter.className} flex flex-col bg-[#020617]`}
                >
                    <NextTopLoader color="#7936EC" showSpinner={false} />
                    <Navbar />
                    <main className="my-24 flex flex-col gap-48 items-center ">
                        {children}
                    </main>
                    <Toaster />
                </body>
            </html>
        </ReactQueryProvider>
    );
}
