import React from "react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/server/trpc/Provider";
import Navbar from "@/components/homepage/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryProvider>
            <html lang="en">
                <body className={`${inter.className} flex flex-col`}>
                    <Navbar />
                    <main className="relative p-24">{children}</main>
                    <Toaster richColors />
                </body>
            </html>
        </ReactQueryProvider>
    );
}
