// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
    BaseClientOptions,
    SchemaInference,
    XataRecord,
} from "@xata.io/client";

const tables = [
    {
        name: "project",
        columns: [
            {
                name: "id",
                type: "uuid",
                notNull: true,
                unique: true,
                defaultValue: "gen_random_uuid()",
            },
            {
                name: "name",
                type: "varchar",
                notNull: true,
                unique: false,
                defaultValue: null,
            },
        ],
    },
    {
        name: "user",
        columns: [
            {
                name: "email",
                type: "varchar",
                notNull: true,
                unique: false,
                defaultValue: null,
            },
            {
                name: "id",
                type: "uuid",
                notNull: true,
                unique: true,
                defaultValue: "gen_random_uuid()",
            },
            {
                name: "kinde_id",
                type: "varchar",
                notNull: true,
                unique: false,
                defaultValue: null,
            },
            {
                name: "name",
                type: "varchar",
                notNull: true,
                unique: false,
                defaultValue: null,
            },
            {
                name: "picture",
                type: "varchar",
                notNull: true,
                unique: false,
                defaultValue: null,
            },
        ],
    },
] as const;

export type SchemaTables = typeof tables;
// @ts-expect-error - generated types
export type InferredTypes = SchemaInference<SchemaTables>;

export type Project = InferredTypes["project"];
export type ProjectRecord = Project & XataRecord;

export type User = InferredTypes["user"];
export type UserRecord = User & XataRecord;

export type DatabaseSchema = {
    project: ProjectRecord;
    user: UserRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
    databaseURL: process.env.XATA_DATABASE_URL,
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
    constructor(options?: BaseClientOptions) {
        // @ts-expect-error - generated types
        super({ ...defaultOptions, ...options }, tables);
    }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
    if (instance) return instance;

    instance = new XataClient();
    return instance;
};
